<section class=legal>
<h2>Mentions Légales</h2>

    <h3>Éditeur du Site</h3>
    <p>
        Nom : Olivier Charlet<br>

    </p>

    <h3>Hébergeur du Site</h3>
    <p>3WAcademy.</p>

    <h3>Responsabilité Éditoriale</h3>
    <p>
        Directeur de la publication : Olivier Charlet<br>
        Responsable de la rédaction : Olivier Charlet
    </p>

    <h3>Données Personnelles</h3>
    <p>
        Conformément à la loi Informatique et Libertés du 6 janvier 1978<br>
        modifiée et au Règlement Général sur la Protection des Données (RGPD),<br>
        vous disposez d’un droit d’accès, de rectification et de suppression des données vous concernant.<br>
        Vous pouvez exercer ces droits en nous contactant à olivier.charlet@3wa.io<br>
    </p>
    <p>
        Délégué à la Protection des Données : Olivier Charlet
    </p>

    <h3>Propriété Intellectuelle</h3>
    <p>
        Tous les contenus présents sur ce site sont la propriété exclusive d'Olivier Charlet,<br>
        sauf mention contraire. Toute reproduction, représentation, modification, publication,<br>
        adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé,<br>
        est interdite, sauf autorisation écrite préalable d'Olivier Charlet.
    </p>

    <h3>Conditions d'Utilisation</h3>
    <p>
        L’utilisation de ce site implique l’acceptation pleine et entière des conditions générales d’utilisation décrites ci-après.<br>
        Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment.
    </p>

    <h3>Cookies</h3>
    <p>
        Ce site utilise des cookies pour améliorer l'expérience utilisateur.<br>
        En naviguant sur ce site, vous acceptez l'utilisation des cookies.<br>
        Vous pouvez à tout moment modifier les paramètres de votre navigateur pour refuser les cookies.
    </p>

    <h3>Création du Site</h3>
    <p>
        Ce site a été conçu par Olivier Charlet, apprenant à la 3WAcademy, pour un projet de fin d'année.
    </p>
    
    <h3>Remerciements</h3>
    <p>
        Un grand merci à Coline Charlet pour les magnifiques dessins qui embellissent ce site.
    </p>
</section>